# Generated by Django 2.0.4 on 2018-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.CharField(default='John Doe', max_length=50),
        ),
    ]
